// <auto-generated />
namespace webproje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration38 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration38));
        
        string IMigrationMetadata.Id
        {
            get { return "202212161855332_migration38"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
